### ISSUE TITLE
BLE_Proximity_Sensor off.

### ISSUE THREAD

**Issue by kolet** [SensorsIot/Bluetooth-BLE-on-Arduino-IDE#10]
so, i've tried to use BLE_Proximity_Sensor.ino on my nodemcu 32s (esp32) , 
however when flashing the esp with the ino file the only output from the serial is 

> BLE Scan restarted.....
> off
> 
> BLE Scan restarted.....
> off
> 
> BLE Scan restarted.....
> 

![image](https://user-images.githubusercontent.com/17353839/49342831-aa5c2f80-f668-11e8-8b07-e068396a17ee.png)

no devices as been found. (when they are at least 2 )

any ideas ?

**Comment by SensorsIot** [comment]
No, no idea.
