### ISSUE TITLE
Client BLE ESP32 don't discover Services and Characteristics

### ISSUE THREAD

**Issue by hugocarmona7** [SensorsIot/Bluetooth-BLE-on-Arduino-IDE#11]
When I'm trying to test client Sketch my devices discover devices but it doesn't seems any Services UUID or UUID Char, any idea? 

Thank you so much.

**Comment by SensorsIot** [comment]
Unfortunately, I cannot support my projects. The BLE part of the ESP32 is in constant development. So it is possible they broke something.
