### ISSUE TITLE
Bluetooth fail to restart

### ISSUE THREAD

**Issue by jamesee** [SensorsIot/Bluetooth-BLE-on-Arduino-IDE#12]
Hi

Thank you for the wonderful youtube tutorial and code.

I downloaded your code and tried it on esp32. I noticed that the code perform great from the first bluetooth scan and subsequent wifi connection (including MQTT publish), but it seems to fail to reconnect bluetooth after that and failed to perform bluetooth scan.

May I know whether you have noticed it and whether you have any way to rectify it.

Many thanks

James

**Comment by SensorsIot** [comment]
This is an old video and unfortunately I do not have the time to check it. The ESP32 developer frequently change their code, so it can happen that you have problems.
