### ISSUE TITLE
PubSubClient.h: No such file or directory

### ISSUE THREAD

**Issue by ralong777** [SensorsIot/Bluetooth-BLE-on-Arduino-IDE#15]
Hi i just installed arduino ide and cant run compilation on this program. I have this error message:

sketch_sep21a:25:26: fatal error: PubSubClient.h: No such file or directory
Multiple libraries were found for "WiFi.h"
compilation terminated.
 Used: C:\Users\Oskar\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.51.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
PubSubClient.h: No such file or directory

**Comment by SensorsIot** [comment]
You need to install the PubSub library. The other is only a warning.
