### ISSUE TITLE
Missing Wifi connection !

### ISSUE THREAD

**Issue by DevThePhoenix** [SensorsIot/Bluetooth-BLE-on-Arduino-IDE#8]
Hi all, I've successfully flashed the code to a esp32 dev board, in terminal it always shows:

BLE Scan restarted.....
BLE Advertised Device found: Name: W307N_C439F59FF5, Address: dd:f5:9f:f5:39:c4, serviceUUID: 7905ff00-b5ce-4e99-a40f-4b1e122d00d0
off

BLE Scan restarted.....
BLE Advertised Device found: Name: W307N_C439F59FF5, Address: dd:f5:9f:f5:39:c4, serviceUUID: 7905ff00-b5ce-4e99-a40f-4b1e122d00d0
off

BLE Scan restarted.....
BLE Advertised Device found: Name: W307N_C439F59FF5, Address: dd:f5:9f:f5:39:c4, serviceUUID: 7905ff00-b5ce-4e99-a40f-4b1e122d00d0
off

the same words repeated again and again..

It seems the esp32 didn't connect to wifi at all(and mqtt of cuz).. Have I done something wrong?
many thanks, please help

**Comment by SensorsIot** [comment]
Unfortunately I cannot do remote debugging :-(
