### ISSUE TITLE
Sketch too big  -  Compiled size too large

### ISSUE THREAD

**Issue by zimpower** [SensorsIot/Bluetooth-BLE-on-Arduino-IDE#9]
Thanks for the sketches / videos btw - very helpful.

I tried your sketch (and other sketches). When trying to combine BLE + MQTT on my WEMOS  I get the error below. 

Is this something anyone else has come across and solved?

> Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
> Error compiling for board "WeMos" WiFi&Bluetooth Battery.

**Comment by ohjay93** [comment]
I get the same error when trying to compile on my Adafruit HUZZAH ESP32 Feather :-(

**Comment by bcyr** [comment]
I got the same problem.  Here is the solution for Arduino : 

Tools --> Partition Scheme:  --> Select No OTA (Large APP)

It works for my M5Stack!

**Comment by daveschafer** [comment]
I also got this error, the Solution from @bcyr did not work out for me.

After some hints from the Issues Page @SensorsIot ,I noticed that the board itself seems to be the problem.
My ESP32 is from Aliexpress and probably not supported well in Arduino IDE.

#### Solution

Search for your boards.txt in esp32 subfolder.
In the boards.txt you have to search for your board (mine was nodemcu-32s).
There you have to change the value:
`nodemcu-32s.upload.maximum_size=1310720`
to
`nodemcu-32s.upload.maximum_size=3407872`

I got the actual max upload size from the manufacteurers website, so be cautious which value you enter here or the code will not work.
